### ISSUE TITLE
Make lewd.sxcu return HTTP 401 when not logged in

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#19]
When accessing /lewd.sxcu while not logged in, the response code is still `HTTP/1.1 200 OK`, even though it tells the user to log in. This should probably be changed to 401 (https://tools.ietf.org/html/rfc7235#section-3.1) or similar

**Comment by inabahare** [comment]
![image](https://user-images.githubusercontent.com/6093917/50573221-e7ceec80-0dcf-11e9-92d8-adf9fbc54609.png)
