### ISSUE TITLE
Hide token unless clicked/hovered

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#20]
![image](https://user-images.githubusercontent.com/6226312/50562828-e4782a00-0d17-11e9-91e0-106b67d28eb2.png)

so you don't accidently show this in screenshots/streams or whatever

**Comment by inabahare** [comment]
[Opa](https://github.com/inabahare/lewd2/commit/82f83f4c1c0af9e19e8177803d8a92c79fbea93f)
