### ISSUE TITLE
"Change password" fields bad input notification

### ISSUE THREAD

**Issue by lz0** [inabahare/lewd2#25]
**What:**
 If you click the [Change password] without any input the errors display the password lengths advised to be different for the two fields meant to be similar.

**Where:** 
[https://lewd.se/user](https://lewd.se/user)

**Expected:** 
The notification fields advising the user should have the same password length suggested for the two fields where the same put is advised.

**Actual:** 
The notification fields advise the user different lengths minimum for the different identical fields.

**Steps to reproduce:** 
1. Be  logged in as user.
2. Navigate to [https://lewd.se/user](https://lewd.se/user) or user landing page.
3. Without any input in the *Change password* fields press the [Change password] button.
4. Observe notification fields two and three.

**Image:** 
![img1](https://u.lewd.se/636a002a5368_firefox_2019-01-01_15-05-30.png)

**Comment by inabahare** [comment]
[dooone~](https://github.com/inabahare/lewd2/commit/f981a4b84fb39a31f12e93bbb21fd5ae9e896636)
