### ISSUE TITLE
Resizing browser window breaks navbar

### ISSUE THREAD

**Issue by lz0** [inabahare/lewd2#27]
**What:**
On desktop certain screen sizes specifically, between width 1023 -1087 px, the navbar goes white in sections but is still functional before transforming into the hamburger type menu

**Where:** 
[https://lewd.se/login](https://lewd.se/login)

**Expected:**
 The navbar consistently scales from a big window into the hamburger menu.

**Actual:** 
Between certain window widths the navbar turns white in certain sections before transforming into the hamburger menu at the lowest width value of the issue.

**Browsers:** 
Firefox Quantum 64.0 (64-bit)
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Steps to reproduce:** 
1. Navigate to [https://lewd.se/login](https://lewd.se/login).
2. Reduce the width of your browser window by scaling it's side horizontally.
3. Between pixel width 1023 - 1087 you should observe the navbar turning white in certain sections rendering it unreadable.

**Image:** 
![img1](https://u.lewd.se/042f780c9cd4_943945b08886_2019-01-01_16-08-03.gif)

**Comment by inabahare** [comment]
Aww yeeeee I finally fixed this shit!!!!!!!

**Comment by inabahare** [comment]
![image](https://user-images.githubusercontent.com/6093917/52478862-07172180-2ba7-11e9-95b9-448b2e27b2d9.png)
