### ISSUE TITLE
Bulk delete option to View Uploads

### ISSUE THREAD

**Issue by lz0** [inabahare/lewd2#47]
I would like suggest a feature request for a bulk delete option for the view uploads page.

* **What is the current behavior?**
[View uploads](https://lewd.se/user/view-uploads) lists the bulk of all our uploads _ever posted_. In the column _delete_ there is a button for every line for us to be able to undo that bad accident of an upload.

* **What change would you have see to the current feature?**
The option to purge my entire upload history and/or be able with for example check boxes to select which uploads I want to remove by hand and additionally maybe multi selecting the uploads you want to remove with `Shift + Click`?

* **What is the motivation / use case for changing the behavior?**
To easier  manage your most recent uploads, be able to purge your upload list quick and easy.

**Comment by inabahare** [comment]
The deed has been done

**Comment by lz0** [comment]
How was this fixed exactly? 🤔

**Comment by inabahare** [comment]
? 

![image](https://user-images.githubusercontent.com/6093917/74663263-b8c63680-519b-11ea-90bf-ab2a4e90bf4d.png)

is it because you want ctrl + click functionality?

**Comment by lz0** [comment]
You are right - this is fixed - as of per implementation of the selection boxes AND delete the selected button. Please see [Select all checkboxes with one button in View Uploads #74](https://github.com/inabahare/lewd2/issues/74) for what I felt was missing.
