### ISSUE TITLE
Deal with duplicate files

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#5]
**Feature**: Link duplicate to original file in DB and reset original files deletion counter
**Other Details**: Not exactly sure how to deal with user deletions, remove that file-ID and replace with the one next in line?

**Comment by inabahare** [comment]
This has been implemented. Duplicate files will first of all update the upload date in the database, then the app will add details of the just uploaded file to the database with a "duplicate" flag set to false. 

If to or more users have uploaded the same file then it won't be possible to delete the file until all users agree. Fortunately that won't really be that difficult to do with SQL.
