### ISSUE TITLE
Make ShareX config name be generated from config

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#56]
https://github.com/inabahare/lewd2/blob/78de804cf278f0e2d9103250230c978638335e7d/src/app/Controllers/index/sharex.js#L13
This should be read from the config here:
https://github.com/inabahare/lewd2/blob/78de804cf278f0e2d9103250230c978638335e7d/.env.dist#L9

**Comment by inabahare** [comment]
Done~
