### ISSUE TITLE
Feature request: random and custom filename

### ISSUE THREAD

**Issue by gphg** [inabahare/lewd2#64]
Basically it works like uguu.se.

Random filename is basically all it did was get rid of the filename part of the upload and only kept the random string. While custom filename let's user decide the filename part.

**Comment by lz0** [comment]
👍

**Comment by CaterpyOwO** [comment]
Yes please, the filenames get kinda long

**Comment by indrakaw** [comment]
*Alas*, It's possible to remove or change the extension on custom filename. This thing is kinda explicit. You should double check the security on this matter.

**Comment by inabahare** [comment]
Need to do something about ShareX tho. Probably a button or something

**Comment by gphg** [comment]
Sorry for necro-posting.

How to randomize filename on curl upload?

**Comment by kattjevfel** [comment]
@gphg `--header "shortUrl: true"`
