### ISSUE TITLE
[feature request] Display uploaded files under upload button

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#8]
Display files under the upload button, like pomf clones do. (it's cool aight?)
Filename to the left and the url to the right, neato~

Example:
![example](https://u.lewd.se/eDgqtG_2018-07-11_12-08-07.png)

**Comment by inabahare** [comment]
![2018-07-15 15-11-42](https://user-images.githubusercontent.com/6093917/42734592-f3718ffc-8846-11e8-9c39-73e355815bde.png)
![2018-07-15_14-07-51](https://user-images.githubusercontent.com/6093917/42734593-f38ed1ac-8846-11e8-9da9-960f705d578f.png)

The deed has been done
